name: CSGO WebAdmin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-restful flask-cors python-valve python-decouple
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Testing with unittest
      run: |
        python -m unittest discover -s tests
      env:
          IP_ADDRESS: 189.126.105.143
          CSGO_PORT: 27015
          PASSWORD: changeme
    - name: "Deployment"
      env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOYKEY }}
          dev_env_file: ${{ secrets.DEVENVFILE }}
          api_dir: "csgo_api"
          front_dir: "csgo_webapp"
          remote_api_dir: "/home/ubuntu/dev/csgo_webadmin"
          remote_front_dir: "/var/www/html"
      run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          echo "$dev_env_file" > .env
          chmod 600 .env
          rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${api_dir} ${remote_user}@${remote_host}:${remote_api_dir}
          rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${front_dir} ${remote_user}@${remote_host}:${remote_front_dir}
          rm ~/.ssh/id_github
